name: Train and Evaluate Model

on:
  push:
    branches:
      - main

jobs:
  train-evaluate-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: make install

    - name: Lint code
      run: make lint

    - name: Format code
      run: make format

    - name: Download Data
      run: make download_data

    - name: Engineer Features
      run: make features

    - name: Train Model
      run: make train

    - name: Evaluate Model
      run: make evaluate

    - name: Deploy Model
      run: make deploy