name: Train and Evaluate Model

on:
  push:
    branches:
      - main

jobs:
  train-evaluate-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get install -y make
        make init
    - name: Download Data
      run: make data

    - name: Engineer Features
      run: make features

    - name: Train Model
      run: make train

    - name: Evaluate Model
      run: make evaluate

    - name: Deploy Model
      run: make deploy
